# Generated by Django 3.0.7 on 2020-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='up_file',
            field=models.FileField(blank=True, null=True, upload_to='files', verbose_name='UPLOAD FILE'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='UPLOAD IMAGE'),
        ),
    ]
