# Generated by Django 3.0.7 on 2020-07-14 11:54

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(blank=True, null=True, verbose_name='app_id')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('genre', models.CharField(max_length=100, verbose_name='genre')),
                ('developer', models.CharField(max_length=100, verbose_name='developer')),
                ('release_at', models.DateTimeField(verbose_name='release Day')),
                ('info', models.TextField(verbose_name='info')),
                ('pc_requirements_minimum', models.CharField(blank=True, max_length=1000, null=True, verbose_name='pc_requirements_minimum')),
                ('pc_requirements_recommended', models.CharField(blank=True, max_length=1000, null=True, verbose_name='pc_requirements_recommended')),
                ('mac_requirements_minimum', models.CharField(blank=True, max_length=1000, null=True, verbose_name='mac_requirements_minimum')),
                ('mac_requirements_recommended', models.CharField(blank=True, max_length=1000, null=True, verbose_name='mac_requirements_recommended')),
                ('linux_requirements_minimum', models.CharField(blank=True, max_length=1000, null=True, verbose_name='linux_requirements_minimum')),
                ('linux_requirements_recommended', models.CharField(blank=True, max_length=1000, null=True, verbose_name='linux_requirements_recommended')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='thumbnail')),
                ('steam', models.IntegerField(blank=True, null=True, verbose_name='steam')),
                ('origin', models.IntegerField(blank=True, null=True, verbose_name='origin')),
                ('uplay', models.IntegerField(blank=True, null=True, verbose_name='uplay')),
                ('epic_games', models.IntegerField(blank=True, null=True, verbose_name='epic_games')),
                ('drmfree', models.IntegerField(blank=True, null=True, verbose_name='drmfree')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_list', models.CharField(max_length=100, verbose_name='genre_list')),
            ],
        ),
    ]
