# Generated by Django 3.0.7 on 2020-07-15 10:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
