# Generated by Django 3.0.7 on 2020-07-15 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='like_users',
            field=models.ManyToManyField(related_name='like_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
