# Generated by Django 3.0.7 on 2020-07-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='board.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
