# Generated by Django 3.0.7 on 2020-07-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200707_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='like_posts',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
