# Generated by Django 3.0.7 on 2020-07-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
